# Generated by Django 4.0.1 on 2024-04-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('alphabet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=500)),
                ('aadhaar', models.CharField(max_length=12)),
                ('certificate', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=500)),
                ('aadhaar', models.CharField(max_length=12)),
                ('udid', models.CharField(max_length=18)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('VIDEO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.video')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=200)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=500)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='myapp.login')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='myapp.login')),
            ],
        ),
    ]
