# Generated by Django 4.0.1 on 2024-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trainer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='aadhaarphoto',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaarphoto',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
