# Generated by Django 4.0.1 on 2024-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainer_aadhaarphoto_user_aadhaarphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
