# Generated by Django 4.0.1 on 2024-05-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_request_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alphabet',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer'),
            preserve_default=False,
        ),
    ]
